@startuml
class Modele implements Sujet{
-FileComposite file
-List observateurs
-String introspection
+Modele(FileComposite): 
+getPackage(Class): String
+enregistrerObservateur(Observateur): void
+getHeritage(Class): String
+getAffichage(int): String
+getIntrospection(): String
+getInterface(Class,String): String
+introspection(String): String
+getAttribut(Field): String
+saveIntrospection(String): void
+notifierObservateur(): void
+getMethodeConstruct(Executable): String
+supprimerObservateur(Observateur): void
+getUML(String): String
+getNom(Class): String
+getRacine(): FileComposite
}
@enduml