@startuml
class CrazyFrog {
+CrazyFrog()
+CombienCaCoute():double
+getLogo():MyImage
}

class Lunettes {
+Lunettes(Logo)
+CombienCaCoute():double
+getLogo():MyImage
}

class ReneLaTaupe {
+ReneLaTaupe()
+CombienCaCoute():double
+getLogo():MyImage
}

class MyImage {
+MyImage(MyImage)
+MyImage(String)
+display():void
#paintComponent(Graphics):void
+textOver(String,int,int):void
+paintOver(String,int,int):void
}

CrazyFrog -u-|> Logo : ""
Lunettes -u-|> DecorateurImage : ""
ReneLaTaupe -u-|> Logo : ""
MyImage "1" ..> "1" BufferedImage : image
MyImage "1" ..> "1" Dimension : size
MyImage -u-|> JPanel : ""
@enduml